from typing import Dict, Any

from final_filter.abc_filtering_module import FilteringModule

IGNORED_PO_PAIRS = {
    ("/r/Synonym", "known"),
    ("/r/Synonym", "called"),

    ("/r/SimilarTo", "similar"),
    ("/r/SimilarTo", "the same"),
    ("/r/SimilarTo", "same"),
    ("/r/SimilarTo", "identical"),
    ("/r/SimilarTo", "same one"),
    ("/r/SimilarTo", "each other"),
    ("/r/SimilarTo", "last year"),

    ("/r/DistinctFrom", "each other"),
    ("/r/DistinctFrom", "last year"),

    ("/r/PartOf", "part"),

    ("/r/MotivatedByGoal", "motivated"),

    ("/r/LocatedNear", "near"),

    ("/r/Antonym", "opposed"),

    ("/r/AtLocation", "fact"),
    ("/r/AtLocation", "use"),
    ("/r/AtLocation", "order"),
    ("/r/AtLocation", "fault"),
    ("/r/AtLocation", "trouble"),
    ("/r/AtLocation", "area"),
    ("/r/AtLocation", "the area"),
    ("/r/AtLocation", "display"),
    ("/r/AtLocation", "touch"),
    ("/r/AtLocation", "same time"),
    ("/r/AtLocation", "charge"),
    ("/r/AtLocation", "demand"),
    ("/r/AtLocation", "risk"),
    ("/r/AtLocation", "business"),
    ("/r/AtLocation", "contact"),
    ("/r/AtLocation", "frequent contact"),
    ("/r/AtLocation", "touch"),
    ("/r/AtLocation", "the moment"),
    ("/r/AtLocation", "time"),
    ("/r/AtLocation", "real time"),
    ("/r/AtLocation", "given time"),
    ("/r/AtLocation", "sight"),
    ("/r/AtLocation", "hurry"),
    ("/r/AtLocation", "need"),
    ("/r/AtLocation", "control"),
    ("/r/AtLocation", "first place"),
    ("/r/AtLocation", "the top of their game"),
    ("/r/AtLocation", "the top of their games"),
    ("/r/AtLocation", "crisis"),
    ("/r/AtLocation", "debt"),
    ("/r/AtLocation", "advantage"),
    ("/r/AtLocation", "disadvantage"),
    ("/r/AtLocation", "this point"),
    ("/r/AtLocation", "the past"),
    ("/r/AtLocation", "the future"),
    ("/r/AtLocation", "service"),
    ("/r/AtLocation", "motion"),
    ("/r/AtLocation", "rest"),
    ("/r/AtLocation", "work"),
    ("/r/AtLocation", "the game"),
    ("/r/AtLocation", "game"),
    ("/r/AtLocation", "shock"),
    ("/r/AtLocation", "agreement"),
    ("/r/AtLocation", "news"),
    ("/r/AtLocation", "the news"),
    ("/r/AtLocation", "the end of the day"),
    ("/r/AtLocation", "the mood"),
    ("/r/AtLocation", "good mood"),
    ("/r/AtLocation", "bad mood"),
    ("/r/AtLocation", "pain"),
    ("/r/AtLocation", "home"),
    ("/r/AtLocation", "the way"),
    ("/r/AtLocation", "many ways"),
    ("/r/AtLocation", "addition"),
    ("/r/AtLocation", "weekend"),
    ("/r/AtLocation", "weekday"),
    ("/r/AtLocation", "reverse"),
    ("/r/AtLocation", "control"),
    ("/r/AtLocation", "our control"),
    ("/r/AtLocation", "front of us"),
    ("/r/AtLocation", "front of you"),
    ("/r/AtLocation", "possession"),
    ("/r/AtLocation", "season"),
    ("/r/AtLocation", "room temperature"),
    ("/r/AtLocation", "bloom"),
    ("/r/AtLocation", "our soul"),
    ("/r/AtLocation", "detail"),
    ("/r/AtLocation", "next place"),
    ("/r/AtLocation", "the beginning"),
    ("/r/AtLocation", "the becoming"),
    ("/r/AtLocation", "nature"),
    ("/r/AtLocation", "odd"),
    ("/r/AtLocation", "loss"),
    ("/r/AtLocation", "practice"),
    ("/r/AtLocation", "an all time"),
    ("/r/AtLocation", "an all time high"),
    ("/r/AtLocation", "an all-time high"),
    ("/r/AtLocation", "level"),
    ("/r/AtLocation", "production"),
    ("/r/AtLocation", "stock"),
    ("/r/AtLocation", "the end"),
    ("/r/AtLocation", "the end of the day"),
    ("/r/AtLocation", "order"),
    ("/r/AtLocation", "working order"),
    ("/r/AtLocation", "good working order"),
    ("/r/AtLocation", "line"),
    ("/r/AtLocation", "person"),
    ("/r/AtLocation", "relationship"),
    ("/r/AtLocation", "good condition"),
    ("/r/AtLocation", "bad condition"),
    ("/r/AtLocation", "operation"),
    ("/r/AtLocation", "standby"),
    ("/r/AtLocation", "orientation"),
    ("/r/AtLocation", "existence"),
    ("/r/AtLocation", "place"),
    ("/r/AtLocation", "residence"),
    ("/r/AtLocation", "fine voice"),
    ("/r/AtLocation", "session"),
    ("/r/AtLocation", "the final"),
    ("/r/AtLocation", "age"),
    ("/r/AtLocation", "tear"),
    ("/r/AtLocation", "risk"),
    ("/r/AtLocation", "high risk"),
    ("/r/AtLocation", "higher risk"),
    ("/r/AtLocation", "low risk"),
    ("/r/AtLocation", "lower risk"),
    ("/r/AtLocation", "awe"),
    ("/r/AtLocation", "poverty"),
    ("/r/AtLocation", "grade"),
    ("/r/AtLocation", "year"),
    ("/r/AtLocation", "month"),
    ("/r/AtLocation", "day"),
    ("/r/AtLocation", "their element"),
    ("/r/AtLocation", "element"),
    ("/r/AtLocation", "their teens"),
    ("/r/AtLocation", "action"),
    ("/r/AtLocation", "the wrong"),
    ("/r/AtLocation", "the lead"),
    ("/r/AtLocation", "the lead"),
    ("/r/AtLocation", "discussion"),
    ("/r/AtLocation", "negotiation"),
    ("/r/AtLocation", "the business"),
    ("/r/AtLocation", "mile"),
    ("/r/AtLocation", "the fall"),
    ("/r/AtLocation", "full force"),
    ("/r/AtLocation", "the top of the list"),
    ("/r/AtLocation", "peak"),
    ("/r/AtLocation", "their peak"),
    ("/r/AtLocation", "its peak"),
    ("/r/AtLocation", "their prime"),
    ("/r/AtLocation", "its prime"),
    ("/r/AtLocation", "prime"),
    ("/r/AtLocation", "daily use"),
    ("/r/AtLocation", "capacity"),
    ("/r/AtLocation", "the forefront"),

    ("/r/AtLocation", "english"),
    ("/r/AtLocation", "german"),
    ("/r/AtLocation", "french"),
    ("/r/AtLocation", "chinese"),
    ("/r/AtLocation", "spanish"),
    ("/r/AtLocation", "portuguese"),
    ("/r/AtLocation", "vietnamese"),
    ("/r/AtLocation", "korean"),
    ("/r/AtLocation", "japanese"),
    ("/r/AtLocation", "italian"),
    ("/r/AtLocation", "thai"),
    ("/r/AtLocation", "indonesian"),
    ("/r/AtLocation", "hindi"),
    ("/r/AtLocation", "hindu"),
    ("/r/AtLocation", "arabic"),
    ("/r/AtLocation", "african"),
    ("/r/AtLocation", "afrikaans"),
    ("/r/AtLocation", "russian"),
    ("/r/AtLocation", "dutch"),
    ("/r/AtLocation", "storage"),
    ("/r/AtLocation", "size"),
    ("/r/AtLocation", "late august"),
    ("/r/AtLocation", "default"),
    ("/r/AtLocation", "compliance"),
    ("/r/AtLocation", "liquidation"),
    ("/r/AtLocation", "proximity"),
    ("/r/AtLocation", "state"),
    ("/r/AtLocation", "front"),
    ("/r/AtLocation", "behind"),
    ("/r/AtLocation", "height"),
    ("/r/AtLocation", "weight"),
    ("/r/AtLocation", "full swing"),
    ("/r/AtLocation", "vicinity"),
    ("/r/AtLocation", "the middle"),
    ("/r/AtLocation", "the bottom"),
    ("/r/AtLocation", "the top"),
    ("/r/AtLocation", "chaos"),
    ("/r/AtLocation", "abundance"),
    ("/r/AtLocation", "distance"),
    ("/r/AtLocation", "choice"),
    ("/r/AtLocation", "μm"),
    ("/r/AtLocation", "cm"),
    ("/r/AtLocation", "mm"),
    ("/r/AtLocation", "km"),
    ("/r/AtLocation", "heat"),
    ("/r/AtLocation", "the heat"),
    ("/r/AtLocation", "point"),
    ("/r/AtLocation", "the point"),
    ("/r/AtLocation", "the right"),
    ("/r/AtLocation", "the left"),
    ("/r/AtLocation", "good hands"),
    ("/r/AtLocation", "safe hands"),

    ("/r/AtLocation", "january"),
    ("/r/AtLocation", "february"),
    ("/r/AtLocation", "march"),
    ("/r/AtLocation", "april"),
    ("/r/AtLocation", "may"),
    ("/r/AtLocation", "june"),
    ("/r/AtLocation", "july"),
    ("/r/AtLocation", "august"),
    ("/r/AtLocation", "september"),
    ("/r/AtLocation", "october"),
    ("/r/AtLocation", "november"),
    ("/r/AtLocation", "december"),

    ("/r/UsedFor", "purpose"),
    ("/r/UsedFor", "goal"),
    ("/r/UsedFor", "any goal"),
    ("/r/UsedFor", "any purpose"),
    ("/r/UsedFor", "example"),
    ("/r/UsedFor", "instance"),
    ("/r/UsedFor", "first time"),
    ("/r/UsedFor", "second time"),
    ("/r/UsedFor", "third time"),

    ("/r/HasA", "a lot"),
    ("/r/HasA", "the capacity"),
    ("/r/HasA", "chance"),
    ("/r/HasA", "chances"),
    ("/r/HasA", "the advantage"),
    ("/r/HasA", "advantage"),
    ("/r/HasA", "advantages"),
    ("/r/HasA", "disadvantage"),
    ("/r/HasA", "disadvantages"),
    ("/r/HasA", "the disadvantage"),
    ("/r/HasA", "answer"),
    ("/r/HasA", "trouble"),
    ("/r/HasA", "opportunity"),
    ("/r/HasA", "the opportunity"),
    ("/r/HasA", "the opportunity"),
    ("/r/HasA", "problem"),
    ("/r/HasA", "many problems"),
    ("/r/HasA", "enough"),
    ("/r/HasA", "issue"),
    ("/r/HasA", "many issues"),
    ("/r/HasA", "potentials"),
    ("/r/HasA", "the potential"),

    ("/r/MadeOf", "scratch"),
    ("/r/MadeOf", "part"),
    ("/r/MadeOf", "love"),
    ("/r/MadeOf", "care"),
    ("/r/MadeOf", "start"),
    ("/r/MadeOf", "made"),

    ("/r/CapableOf", "be capable"),
    ("/r/CapableOf", "be able"),
    ("/r/CapableOf", "come in size"),
    ("/r/CapableOf", "play an important role"),
    ("/r/CapableOf", "play important role"),
    ("/r/CapableOf", "make difference"),
    ("/r/CapableOf", "do thing"),
    ("/r/CapableOf", "do the same"),
    ("/r/CapableOf", "take part"),
    ("/r/CapableOf", "give way"),
    ("/r/CapableOf", "give a way"),
    ("/r/CapableOf", "find a way"),
    ("/r/CapableOf", "find way"),
    ("/r/CapableOf", "find its way"),
    ("/r/CapableOf", "find their way"),
    ("/r/CapableOf", "find his way"),
    ("/r/CapableOf", "find her way"),
    ("/r/CapableOf", "make way"),
    ("/r/CapableOf", "make their way"),
    ("/r/CapableOf", "make its way"),
    ("/r/CapableOf", "make his way"),
    ("/r/CapableOf", "make her way"),
    ("/r/CapableOf", "go hand"),
    ("/r/CapableOf", "result"),

    ("/r/HasProperty", "available"),
    ("/r/HasProperty", "different"),
    ("/r/HasProperty", "at risk"),
    ("/r/HasProperty", "first"),
    ("/r/HasProperty", "worth"),
    ("/r/HasProperty", "aware"),
    ("/r/HasProperty", "male"),
    ("/r/HasProperty", "female"),
    ("/r/HasProperty", "similar"),

    ("/r/HasProperty", "english"),
    ("/r/HasProperty", "german"),
    ("/r/HasProperty", "french"),
    ("/r/HasProperty", "chinese"),
    ("/r/HasProperty", "spanish"),
    ("/r/HasProperty", "portuguese"),
    ("/r/HasProperty", "vietnamese"),
    ("/r/HasProperty", "korean"),
    ("/r/HasProperty", "japanese"),
    ("/r/HasProperty", "italian"),
    ("/r/HasProperty", "thai"),
    ("/r/HasProperty", "indonesian"),
    ("/r/HasProperty", "hindi"),
    ("/r/HasProperty", "hindu"),
    ("/r/HasProperty", "arabic"),
    ("/r/HasProperty", "american"),
    ("/r/HasProperty", "european"),
    ("/r/HasProperty", "mexican"),
    ("/r/HasProperty", "singaporean"),
    ("/r/HasProperty", "african"),
    ("/r/HasProperty", "afrikaans"),
    ("/r/HasProperty", "russian"),
    ("/r/HasProperty", "canadian"),
    ("/r/HasProperty", "australian"),
    ("/r/HasProperty", "aussie"),
    ("/r/HasProperty", "dutch"),

    # origins
    ("/r/HasProperty", "afghan"),
    ("/r/HasProperty", "african"),
    ("/r/HasProperty", "african american"),
    ("/r/HasProperty", "african americans"),
    ("/r/HasProperty", "albanian"),
    ("/r/HasProperty", "american"),
    ("/r/HasProperty", "argentian"),
    ("/r/HasProperty", "armenian"),
    ("/r/HasProperty", "asian"),
    ("/r/HasProperty", "australian"),
    ("/r/HasProperty", "austrian"),
    ("/r/HasProperty", "bangladesh"),
    ("/r/HasProperty", "bengali"),
    ("/r/HasProperty", "bolivian"),
    ("/r/HasProperty", "brazilian"),
    ("/r/HasProperty", "british"),
    ("/r/HasProperty", "cameroonian"),
    ("/r/HasProperty", "cape verdean"),
    ("/r/HasProperty", "chilean"),
    ("/r/HasProperty", "chinese"),
    ("/r/HasProperty", "columbian"),
    ("/r/HasProperty", "crimean"),
    ("/r/HasProperty", "dutch"),
    ("/r/HasProperty", "ecuadorian"),
    ("/r/HasProperty", "egyptian"),
    ("/r/HasProperty", "english"),
    ("/r/HasProperty", "eritrean"),
    ("/r/HasProperty", "ethiopian"),
    ("/r/HasProperty", "european"),
    ("/r/HasProperty", "filipino"),
    ("/r/HasProperty", "finnish"),
    ("/r/HasProperty", "french"),
    ("/r/HasProperty", "german"),
    ("/r/HasProperty", "ghanaian"),
    ("/r/HasProperty", "greek"),
    ("/r/HasProperty", "guatemalan"),
    ("/r/HasProperty", "hispanic"),
    ("/r/HasProperty", "indian"),
    ("/r/HasProperty", "indonesian"),
    ("/r/HasProperty", "iranian"),
    ("/r/HasProperty", "iraqi"),
    ("/r/HasProperty", "irish"),
    ("/r/HasProperty", "israeli"),
    ("/r/HasProperty", "italian"),
    ("/r/HasProperty", "japanese"),
    ("/r/HasProperty", "jordanian"),
    ("/r/HasProperty", "kenyan"),
    ("/r/HasProperty", "korean"),
    ("/r/HasProperty", "laotian"),
    ("/r/HasProperty", "lebanese"),
    ("/r/HasProperty", "liberian"),
    ("/r/HasProperty", "mexican"),
    ("/r/HasProperty", "moroccan"),
    ("/r/HasProperty", "native american"),
    ("/r/HasProperty", "nepali"),
    ("/r/HasProperty", "nigerian"),
    ("/r/HasProperty", "norwegian"),
    ("/r/HasProperty", "omani"),
    ("/r/HasProperty", "pakistani"),
    ("/r/HasProperty", "paraguayan"),
    ("/r/HasProperty", "persian"),
    ("/r/HasProperty", "peruvian"),
    ("/r/HasProperty", "polish"),
    ("/r/HasProperty", "portuguese"),
    ("/r/HasProperty", "puerto rican"),
    ("/r/HasProperty", "qatari"),
    ("/r/HasProperty", "romanian"),
    ("/r/HasProperty", "russian"),
    ("/r/HasProperty", "saudi arabian"),
    ("/r/HasProperty", "scottish"),
    ("/r/HasProperty", "sierra leonean"),
    ("/r/HasProperty", "singaporean"),
    ("/r/HasProperty", "somali"),
    ("/r/HasProperty", "south african"),
    ("/r/HasProperty", "spanish"),
    ("/r/HasProperty", "sudanese"),
    ("/r/HasProperty", "swedish"),
    ("/r/HasProperty", "syrian"),
    ("/r/HasProperty", "taiwanese"),
    ("/r/HasProperty", "turkish"),
    ("/r/HasProperty", "ukrainian"),
    ("/r/HasProperty", "venezuelan"),
    ("/r/HasProperty", "vietnamese"),
    ("/r/HasProperty", "yemeni"),
    ("/r/HasProperty", "zambian"),

    # religion
    ("/r/HasProperty", "christian"),
    ("/r/HasProperty", "muslim"),
    ("/r/HasProperty", "islam"),
    ("/r/HasProperty", "buddhist"),

    ("/r/HasPrerequisite", "help"),
    ("/r/HasPrerequisite", "our help"),
    ("/r/HasPrerequisite", "more time"),

    ("/r/DefinedAs", "defined"),

    ("/r/Causes", "cause"),
    ("/r/Causes", "increase"),
    ("/r/Causes", "decrease"),
    ("/r/Causes", "problem"),
    ("/r/Causes", "the problem"),
    ("/r/Causes", "problems"),
    ("/r/Causes", "issue"),
    ("/r/Causes", "the issue"),
    ("/r/Causes", "the issue"),
    ("/r/Causes", "issues"),
    ("/r/Causes", "the issues"),

    ("/r/IsA", "the place"),
    ("/r/IsA", "many things"),

    ("/r/ReceivesAction", "told"),
    ("/r/ReceivesAction", "said"),
    ("/r/ReceivesAction", "considered"),
    ("/r/ReceivesAction", "asked"),
    ("/r/ReceivesAction", "given"),
    ("/r/ReceivesAction", "assigned"),
    ("/r/ReceivesAction", "left"),
    ("/r/ReceivesAction", "included"),
    ("/r/ReceivesAction", "involved"),
}


class IgnorePOModule(FilteringModule):
    def __init__(self):
        self.ignored_po_pairs = IGNORED_PO_PAIRS

    def validate(self, cluster: Dict[str, Any]) -> bool:
        relation = cluster["predicted_relation"]
        arg2 = cluster["predicted_object"]

        return (relation, arg2) not in self.ignored_po_pairs

    def get_name(self):
        return f"IgnorePOModule - {len(self.ignored_po_pairs)} PO pairs"
